# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: classifier.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'classifier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63lassifier.proto\x12\nclassifier\"\'\n\x0ePredictRequest\x12\x15\n\roriginal_text\x18\x01 \x01(\t\"#\n\x0fPredictResponse\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t2T\n\x0cProtoService\x12\x44\n\x07Predict\x12\x1a.classifier.PredictRequest\x1a\x1b.classifier.PredictResponse\"\x00\x42\rZ\x0b/classifierb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013/classifier'
  _globals['_PREDICTREQUEST']._serialized_start=32
  _globals['_PREDICTREQUEST']._serialized_end=71
  _globals['_PREDICTRESPONSE']._serialized_start=73
  _globals['_PREDICTRESPONSE']._serialized_end=108
  _globals['_PROTOSERVICE']._serialized_start=110
  _globals['_PROTOSERVICE']._serialized_end=194
# @@protoc_insertion_point(module_scope)
