version: "3.9"

services:
  app:
    build: .
    container_name: guide-bot-app
    environment:
      - API_KEY=YOUR_TOKEN
    depends_on:
      - postgres

  postgres:
    image: postgres:15.5
    container_name: guide-bot-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: guide-bot
    ports:
      - "5500:5432"
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/
      - guide-bot-db:/var/lib/postgresql/data

volumes:
  guide-bot-db:
  