"postgres-leads":
  "username": "root"
  "host": "postgres-leads"
  "port": 5432
  "dbname": "leads-db"
  "sslmode": "disable"

"grpc-clients":
  "core":
    "host": "brm-core"
    "port": 50000
  "ads":
    "host": "brm-ads"
    "port": 50002
  "notifications":
    "host": "notifications"
    "port": 50005

"grpc-server":
  "network": "tcp"
  "port": 50003
