// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: ads_client.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdsServiceClient is the client API for AdsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdsServiceClient interface {
	GetAdById(ctx context.Context, in *GetAdByIdRequest, opts ...grpc.CallOption) (*GetAdByIdResponse, error)
	GetAdsList(ctx context.Context, in *GetAdsListRequest, opts ...grpc.CallOption) (*GetAdsListResponse, error)
	CreateAd(ctx context.Context, in *CreateAdRequest, opts ...grpc.CallOption) (*CreateAdResponse, error)
	UpdateAd(ctx context.Context, in *UpdateAdRequest, opts ...grpc.CallOption) (*UpdateAdResponse, error)
	DeleteAd(ctx context.Context, in *DeleteAdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateResponse(ctx context.Context, in *CreateResponseRequest, opts ...grpc.CallOption) (*CreateResponseResponse, error)
	GetResponses(ctx context.Context, in *GetResponsesRequest, opts ...grpc.CallOption) (*GetResponsesResponse, error)
	GetIndustries(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetIndustriesResponse, error)
}

type adsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdsServiceClient(cc grpc.ClientConnInterface) AdsServiceClient {
	return &adsServiceClient{cc}
}

func (c *adsServiceClient) GetAdById(ctx context.Context, in *GetAdByIdRequest, opts ...grpc.CallOption) (*GetAdByIdResponse, error) {
	out := new(GetAdByIdResponse)
	err := c.cc.Invoke(ctx, "/ads.AdsService/GetAdById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adsServiceClient) GetAdsList(ctx context.Context, in *GetAdsListRequest, opts ...grpc.CallOption) (*GetAdsListResponse, error) {
	out := new(GetAdsListResponse)
	err := c.cc.Invoke(ctx, "/ads.AdsService/GetAdsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adsServiceClient) CreateAd(ctx context.Context, in *CreateAdRequest, opts ...grpc.CallOption) (*CreateAdResponse, error) {
	out := new(CreateAdResponse)
	err := c.cc.Invoke(ctx, "/ads.AdsService/CreateAd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adsServiceClient) UpdateAd(ctx context.Context, in *UpdateAdRequest, opts ...grpc.CallOption) (*UpdateAdResponse, error) {
	out := new(UpdateAdResponse)
	err := c.cc.Invoke(ctx, "/ads.AdsService/UpdateAd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adsServiceClient) DeleteAd(ctx context.Context, in *DeleteAdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/ads.AdsService/DeleteAd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adsServiceClient) CreateResponse(ctx context.Context, in *CreateResponseRequest, opts ...grpc.CallOption) (*CreateResponseResponse, error) {
	out := new(CreateResponseResponse)
	err := c.cc.Invoke(ctx, "/ads.AdsService/CreateResponse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adsServiceClient) GetResponses(ctx context.Context, in *GetResponsesRequest, opts ...grpc.CallOption) (*GetResponsesResponse, error) {
	out := new(GetResponsesResponse)
	err := c.cc.Invoke(ctx, "/ads.AdsService/GetResponses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adsServiceClient) GetIndustries(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetIndustriesResponse, error) {
	out := new(GetIndustriesResponse)
	err := c.cc.Invoke(ctx, "/ads.AdsService/GetIndustries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdsServiceServer is the server API for AdsService service.
// All implementations should embed UnimplementedAdsServiceServer
// for forward compatibility
type AdsServiceServer interface {
	GetAdById(context.Context, *GetAdByIdRequest) (*GetAdByIdResponse, error)
	GetAdsList(context.Context, *GetAdsListRequest) (*GetAdsListResponse, error)
	CreateAd(context.Context, *CreateAdRequest) (*CreateAdResponse, error)
	UpdateAd(context.Context, *UpdateAdRequest) (*UpdateAdResponse, error)
	DeleteAd(context.Context, *DeleteAdRequest) (*emptypb.Empty, error)
	CreateResponse(context.Context, *CreateResponseRequest) (*CreateResponseResponse, error)
	GetResponses(context.Context, *GetResponsesRequest) (*GetResponsesResponse, error)
	GetIndustries(context.Context, *emptypb.Empty) (*GetIndustriesResponse, error)
}

// UnimplementedAdsServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAdsServiceServer struct {
}

func (UnimplementedAdsServiceServer) GetAdById(context.Context, *GetAdByIdRequest) (*GetAdByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdById not implemented")
}
func (UnimplementedAdsServiceServer) GetAdsList(context.Context, *GetAdsListRequest) (*GetAdsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdsList not implemented")
}
func (UnimplementedAdsServiceServer) CreateAd(context.Context, *CreateAdRequest) (*CreateAdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAd not implemented")
}
func (UnimplementedAdsServiceServer) UpdateAd(context.Context, *UpdateAdRequest) (*UpdateAdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAd not implemented")
}
func (UnimplementedAdsServiceServer) DeleteAd(context.Context, *DeleteAdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAd not implemented")
}
func (UnimplementedAdsServiceServer) CreateResponse(context.Context, *CreateResponseRequest) (*CreateResponseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateResponse not implemented")
}
func (UnimplementedAdsServiceServer) GetResponses(context.Context, *GetResponsesRequest) (*GetResponsesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResponses not implemented")
}
func (UnimplementedAdsServiceServer) GetIndustries(context.Context, *emptypb.Empty) (*GetIndustriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIndustries not implemented")
}

// UnsafeAdsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdsServiceServer will
// result in compilation errors.
type UnsafeAdsServiceServer interface {
	mustEmbedUnimplementedAdsServiceServer()
}

func RegisterAdsServiceServer(s grpc.ServiceRegistrar, srv AdsServiceServer) {
	s.RegisterService(&AdsService_ServiceDesc, srv)
}

func _AdsService_GetAdById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).GetAdById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ads.AdsService/GetAdById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).GetAdById(ctx, req.(*GetAdByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdsService_GetAdsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).GetAdsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ads.AdsService/GetAdsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).GetAdsList(ctx, req.(*GetAdsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdsService_CreateAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).CreateAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ads.AdsService/CreateAd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).CreateAd(ctx, req.(*CreateAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdsService_UpdateAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).UpdateAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ads.AdsService/UpdateAd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).UpdateAd(ctx, req.(*UpdateAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdsService_DeleteAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).DeleteAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ads.AdsService/DeleteAd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).DeleteAd(ctx, req.(*DeleteAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdsService_CreateResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).CreateResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ads.AdsService/CreateResponse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).CreateResponse(ctx, req.(*CreateResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdsService_GetResponses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResponsesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).GetResponses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ads.AdsService/GetResponses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).GetResponses(ctx, req.(*GetResponsesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdsService_GetIndustries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).GetIndustries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ads.AdsService/GetIndustries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).GetIndustries(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AdsService_ServiceDesc is the grpc.ServiceDesc for AdsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ads.AdsService",
	HandlerType: (*AdsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdById",
			Handler:    _AdsService_GetAdById_Handler,
		},
		{
			MethodName: "GetAdsList",
			Handler:    _AdsService_GetAdsList_Handler,
		},
		{
			MethodName: "CreateAd",
			Handler:    _AdsService_CreateAd_Handler,
		},
		{
			MethodName: "UpdateAd",
			Handler:    _AdsService_UpdateAd_Handler,
		},
		{
			MethodName: "DeleteAd",
			Handler:    _AdsService_DeleteAd_Handler,
		},
		{
			MethodName: "CreateResponse",
			Handler:    _AdsService_CreateResponse_Handler,
		},
		{
			MethodName: "GetResponses",
			Handler:    _AdsService_GetResponses_Handler,
		},
		{
			MethodName: "GetIndustries",
			Handler:    _AdsService_GetIndustries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ads_client.proto",
}
