"postgres-notifications":
  "username": "root"
  "host": "postgres-notifications"
  "port": 5432
  "dbname": "notifications-db"
  "sslmode": "disable"

"grpc-clients":
  "stats":
    "host": "stats"
    "port": 50004

"grpc-server":
  "network": "tcp"
  "port": 50005
